mock-data/mock-expected-structures-protvista.ts, mock-data/mock-summary-response-protvista.ts, mock-data/mock-uniprot-data-response.json, src/app/core/configuration.service.spec.ts, src/app/core/configuration.service.ts
* Fixing bug of track colours
* Restoring unit tests
Co-authored-by: Mihaly Varadi <mvaradi@ebi.ac.uk>
=> Development (#36)

README.md, src/app/app-header/app-header.component.css, src/app/app-header/app-header.component.html, src/app/app-header/app-header.component.ts, src/app/app.module.ts, src/app/docs/docs.component.css, src/app/docs/docs.component.html, src/app/guidelines/guidelines.component.css, src/app/guidelines/guidelines.component.html, src/app/home/home.component.html, src/app/providers/providers.component.ts, src/app/search-header/search-header.component.css, src/app/search/result-section/result-section.component.css, src/app/search/result-section/result-section.component.html, src/app/search/result-section/summary-section/summary-section.component.css, src/app/search/result-section/summary-section/summary-section.component.html, src/app/search/search.component.css, src/app/search/structures-section/structures-section.component.css
[PDBE-5818](https://www.ebi.ac.uk/panda/jira/browse/PDBE-5818) - Fixes and tweaks for 3D-Beacons pages
=> PDBE-5818 - Fixes and tweaks for 3D-Beacons pages

src/app/app-header/app-header.component.css, src/app/app-header/app-header.component.html, src/app/app-header/app-header.component.ts, src/app/docs/docs.component.css, src/app/docs/docs.component.html, src/app/guidelines/guidelines.component.css, src/app/guidelines/guidelines.component.html, src/app/home/home.component.css, src/app/home/home.component.html, src/app/providers/providers.component.css, src/app/providers/providers.component.html, src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search/result-section/result-section.component.css, src/app/search/result-section/result-section.component.html, src/app/search/result-section/result-section.component.spec.ts, src/app/search/result-section/result-section.component.ts, src/app/search/result-section/summary-section/summary-section.component.css, src/app/search/search.component.css, src/app/search/search.component.html, src/app/search/structures-section/structures-section.component.css, src/app/search/structures-section/structures-section.component.html, src/index.html
PDBE-5818 fixes for mobile and tablet view.
=> PDBE-5818 fixes for mobile and tablet view

src/app/providers/providers.component.css, src/app/providers/providers.component.html
PDBE5818 - Provider link css changed for animation effect.
=> PDBE5818 - Provider link css changed for animation effect

src/app/search/result-section/result-section.component.css, src/app/search/result-section/result-section.component.html
=> PDBE5818 Breakline added

src/app/search/search.component.html, src/app/search/structures-section/structures-section.component.css, src/app/search/structures-section/structures-section.component.html
Widen the viewers' Molstar and Protvista.
=> Widen the viewers Molstar and Protvista.

src/app/search/search.component.html, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence-cards/sequence-cards.component.html, src/app/search/sequence/sequence-data-formatter.service.ts
PDBE5499 - old inprogress red statement removed
=> PDBE5499 - old inprogress red statement removed

src/app/app.module.ts, src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.ts, src/app/search/ensembl/ensembl-data-formatter.service.ts, src/app/search/ensembl/ensembl.component.css, src/app/search/ensembl/ensembl.component.html, src/app/search/result-section/summary-section/summary-section.component.ts, src/app/search/search.component.html, src/app/search/sequence/sequence-cards/sequence-cards.component.html, src/app/search/sequence/sequence-cards/sequence-cards.component.ts, src/app/search/sequence/sequence-data-formatter.service.ts, src/app/search/sequence/sequence.component.css, src/app/search/sequence/sequence.component.html
=> PDBE 6017 fixes 3 db updates

src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.ts, src/app/search/ensembl/ensembl.component.css, src/app/search/ensembl/ensembl.component.html, src/app/search/ensembl/ensembl.component.ts, src/app/search/search.component.css, src/app/search/search.component.html, src/app/search/search.component.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence-cards/sequence-cards.component.html, src/app/search/sequence/sequence-data-formatter.service.ts, src/app/search/sequence/sequence.component.css, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.ts
=> PDBE-6017 Fixes 3DB updates

src/app/app.module.ts, src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence.component.ts
=> PDBE-6017-Fixes

src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence-cards/sequence-cards.component.html, src/app/search/sequence/sequence-data-formatter.service.ts, src/app/search/sequence/sequence.component.css
Pdbe 6017 fixes 3 db updates : breakpoint css added
=> Pdbe 6017 fixes 3 db updates : breakpoint css added

src/app/search-header/search-header.component.html
=> 3DB-Disable Ensemble search

src/app/search-header/search-header.component.spec.ts, src/app/search-header/search-header.component.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.spec.ts, src/app/search/sequence/sequence-data-formatter.service.spec.ts, src/app/search/sequence/sequence-data-formatter.service.ts, src/app/search/sequence/sequence.component.ts
PDBE-5499 - Unit test cases added for sequence search component
=> PDBE-5499 - Unit test cases added for sequence search component

src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.ts, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.ts
PDBE-6102 - Loader added till getting job id
=> PDBE-6102 - Loader added till getting job id

src/app/search/result-section/result-section.component.ts, src/app/search/sequence/sequence.component.ts
=> PDBE-6102 Removed consoles

src/app/app.module.ts, src/app/search-header/search-header.component.ts, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.ts
PDBE-6102 - Added retry for jobid API
=> PDBE-6102 - Added retry for jobid API

src/app/app-header/app-header.component.spec.ts, src/app/app-header/app-header.component.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/core/configuration.service.spec.ts, src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.spec.ts, src/app/search/search-pagination/search-pagination.component.spec.ts, src/app/search/search.component.spec.ts, src/app/search/search.component.ts, src/app/search/search.service.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.spec.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.ts, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.spec.ts, src/app/search/sequence/sequence.service.ts, src/app/search/structures-section/structures-section.component.spec.ts
PDBE6102- code coverage increased
=> PDBE6102- code coverage increased

src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.ts, src/app/search/search.component.css, src/app/search/search.component.html, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.ts
Retry issue resolved and unsubscribed the service.
Design issues resolved
=> Retry issue resolved and unsubscribed the service

src/app/search/sequence/sequence.component.ts
=> Blank page issue resolved

src/app/search-header/search-header.component.ts, src/app/search/result-section/result-section.component.ts, src/app/search/sequence/sequence.component.ts, src/app/search/structures-section/structures-section.component.ts
Issue raised for no result block resolved. and summary section Updated for other api values
=> Issue raised for no result block resolved

src/app/search-header/search-header.component.css, src/app/search/sequence/sequence.component.css, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.ts
Error message for retry attempt page implemented
=> Error message for retry attempt page implemented

src/app/docs/docs.component.html, src/app/search/result-section/summary-section/summary-section.service.ts
Documentation change for AlphaFill link
=> Documentation change for alphafill link

.gitignore, src/app/app-header/app-header.component.spec.ts, src/app/app-header/app-header.component.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/core/configuration.service.spec.ts, src/app/docs/docs.component.html, src/app/search-header/search-header.component.css, src/app/search-header/search-header.component.html, src/app/search-header/search-header.component.spec.ts, src/app/search-header/search-header.component.ts, src/app/search/result-section/result-section.component.ts, src/app/search/result-section/summary-section/summary-section.service.ts, src/app/search/search-pagination/search-pagination.component.spec.ts, src/app/search/search.component.css, src/app/search/search.component.html, src/app/search/search.component.spec.ts, src/app/search/search.component.ts, src/app/search/search.service.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.css, src/app/search/sequence/sequence-cards/sequence-cards.component.spec.ts, src/app/search/sequence/sequence-cards/sequence-cards.component.ts, src/app/search/sequence/sequence.component.css, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.spec.ts, src/app/search/sequence/sequence.component.ts, src/app/search/sequence/sequence.service.ts, src/app/search/structures-section/structures-section.component.spec.ts, src/app/search/structures-section/structures-section.component.ts
This releases new sequence search functionality.
- Minor tweaks in sequence search
- Fixed category for AlphaFill
=> Sequence search release

src/app/search/sequence/sequence.component.css, src/app/search/sequence/sequence.component.html, src/app/search/sequence/sequence.component.spec.ts, src/app/search/sequence/sequence.component.ts
=> PDBE-6131 Tooltip added

src/app/search/sequence/sequence-cards/sequence-cards.component.html
Css issue resolved for displaying match accession if there is a space in string
=> Css issue resolved for displaying match accession

src/app/search-header/search-header.component.ts
Undefined string was displayed in search box
=> Undefined string was displayed in search box

README.md
Issue resolved after testing to int - undefined string
=> Issue resolved after testing to int - undefined string

.gitlab-ci.yml, Dockerfile, src/environments/environment.prod.ts
Dynamically modifies dist files to subtitute env variables
=> Adds pipeline for deployment to this  repo
